# Generated by Django 4.1.2 on 2023-01-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='film_turu',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
